### ISSUE TITLE
feature request: Remainder Mechanism

### ISSUE THREAD

**Issue by jflo** [r7kamura/split-tests-by-timings#3]
It seems this action will have a bootstrapping problem, and newly added tests will never be run until they make it into the init test report. (Please feel free to close if this premise is false)

Would it be possible to add a `remainderGlob` pattern that generates another list of test files, and then those not appearing in the downloaded results could be run without being split by duration.

As long as all results get uploaded, subsequent runs should have a timing for the new tests, and they would be included in future reports.

**Comment by r7kamura** [comment]
Thanks  @jflo. Indeed, I had not noticed that the tests added later were not executed... I will try to think of some countermeasures.

**Comment by r7kamura** [comment]
Rather than having a separate glob pattern, it would be better to have the `glob` pattern contain test file paths that are not included in the test report, so that they can be sorted appropriately. I think  CircleCI's split logic has implemented it that way.

In this case, the internal implementation of this action depends on the following tool, so it may be necessary to offer improvements to this tool, or replace it with another tool, or create a suitable one ourself.

- https://github.com/mtsmfm/split-test

Let's take a look at how other tools behave in these situations. Maybe just switching to it will solve the problem. Similar tools that I know of include the following:

- https://github.com/leonid-shevtsov/split_tests
- https://github.com/scruplelesswizard/split-tests

**Comment by r7kamura** [comment]
@mtsmfm Sorry to call you out of the blue, but we're having trouble with the above and was wondering if you have any good ideas about this?

**Comment by mtsmfm** [comment]
Hmm, if newly added test file name is matched with `--tests-glob` pattern, even there's no timing data it should be appeared.

https://github.com/mtsmfm/split-test/blob/54b116acbf91f89fb28d9e3f3279db05212bc385/src/main.rs#L170-L174

Can you give me concreate example?

**Comment by r7kamura** [comment]
I see, it certainly doesn't look like it will cause any problems. I guessed and asked a question without looking into it deeply. Actually, we may have just misunderstood and there might be no particular problem.

Anyway, thanks for the quick response! You have helped us a lot 👍

**Comment by mtsmfm** [comment]
It's my pleasure 😄 

I may have missed something so please let me know if you can provide a reproducible repo/code.

**Comment by jflo** [comment]
in this case, it should be able to run without any artifact for the reports, is that the correct manner of running it the first time?  I will try to add a conditional when running after the artifact download so tests are split the first time, regardless of reports download success.

**Comment by r7kamura** [comment]
Yes, it is normal for the file to fail to download the first time. That is why the `uses: dawidd6/action-download-artifact` example in the README has `continue-on-error: true`. Maybe you followed this and it didn't work?

**Comment by r7kamura** [comment]
It has been some time and I am going to close this issue now. If you are still experiencing problems, please let me know along with any additional information.
