### ISSUE TITLE
Behavior in a subdirectory

### ISSUE THREAD

**Issue by ursm** [r7kamura/split-tests-by-timings#4]
Hello.

I have a Rails application in a subdirectory of my repository (let's call it `/app`). In this case, I think `glob` should be `app/spec/**/*_spec.rb`, but RSpec expects Rails.root to be the working directory, which doesn't make sense. If you have a solution, I'd be happy to hear it.

**Comment by r7kamura** [comment]
Hmmm, I have never been in that situation and I don't have a good solution at the moment. I guess the dirty way would be like to create a simlink from /spec to /app/spec before executing the action.

**Comment by r7kamura** [comment]
I looked into the `working-directory` option, but it seems that this cannot be specified in `uses` unfortunately

- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
- similar discussion here: https://github.com/actions/github-script/issues/426

**Comment by hoshinotsuyoshi** [comment]
I came across https://github.com/mtsmfm/split-test while checking out https://github.com/r7kamura/split-tests-by-timings. Since the subdirectory paths weren’t working well, I ended up using https://github.com/mtsmfm/split-test directly(and it worked great). I’m not involved with that internal project at my company anymore, but I’d love to give version v0.3.0+ a try sometime. Anyway, thanks a bunch for keeping it maintained! :heart:
